### ISSUE TITLE
Keyframe jumps several seconds

### ISSUE THREAD

**Issue by xNissX233** [aerobounce/trim.lua#11]
The keyframe shortcut doesn't jump from frame to frame, it jumps like 2 seconds, which is redundant with the "jump x seconds" shortcuts.

**Comment by xNissX233** [comment]
With video file

    LEFT Seek backward by keyframe (Minimum distance)
    RIGHT Seek forward by keyframe (Minimum distance)
    UP Seek forward by keyframe (Larger distance)
    DOWN Seek backward by keyframe (Larger distance)

Both the minimum and the larger distance shortcuts jumps 5 seconds.

**Comment by aerobounce** [comment]
As the amount of / the distance between keyframes varies depending on video files, that's how `mpv` understands your file.
But if you want to adjust distances associated to the keys, you can. Take a look at: https://github.com/aerobounce/trim.lua/blob/473c9b1a9900c617ee7bb78521906090b15868d4/trim.lua#L72-L80
You'll find `seekByKeyframes(-0.1)` `seekByKeyframes(0.1)`... etc. You can change those values as you like.

**Comment by xNissX233** [comment]
I made a fork using frame-step instead of "seek" when seeking frame by frame, which honestly makes more sense, and it's way better to find the exact frame I want the file to start and end. I would recommend you to do the same, and it would be also useful for me since I implemented it very quick and maybe it has bugs in some cases, but it's your decision.

**Comment by aerobounce** [comment]
This script is committed to valid video clip creation, so `frame-step` was not the option.
It's good you found your way anyway.
