### ISSUE TITLE
ffmpeg and ffprobe paths are hard-coded

### ISSUE THREAD

**Issue by aerobounce** [aerobounce/trim.lua#3]
## Relevant lines
https://github.com/aerobounce/trim.lua/blob/096a2b99c9debd2a4ba68f45cf5b81373ded28a0/trim.lua#L100
https://github.com/aerobounce/trim.lua/blob/096a2b99c9debd2a4ba68f45cf5b81373ded28a0/trim.lua#L225

**Comment by ScribbleGhost** [comment]
I am on a Windows computer. Does this mean I should change the path?

**Comment by aerobounce** [comment]
This is the same issue of #5.

And yes, you are likely have to change them.
Let's say you have `ffmpeg` at `C:\ffmpeg.exe` , then you need to rewrite the line 225 to `C:\ffmpeg.exe`.
(Note that I'm not familiar with the correct expression of paths in Windows platform, the format above might be wrong)
