### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by iiiGerardoiii** [aerobounce/trim.lua#4]
I guess this script is only for linux/mac? or am I doing something wrong?

**Comment by aerobounce** [comment]
I can't say yes neither no, I've never tested on Win.
What's clear is, you cannot use it on the fly. ffmpeg paths are hard-coded:
https://github.com/aerobounce/trim.lua/blob/096a2b99c9debd2a4ba68f45cf5b81373ded28a0/trim.lua#L100
https://github.com/aerobounce/trim.lua/blob/096a2b99c9debd2a4ba68f45cf5b81373ded28a0/trim.lua#L225
You need to change them to your ffmpeg bin path.

In case you've already done that, provide log here (Do not paste long lines directly here, use a service like pastebin.com), I might be able to help you.

**Comment by iiiGerardoiii** [comment]
Ah yes, that was it 👍.

changed line 100 to `"C:/Users/gerry boy/Documents/mpv/ffprobe.exe"`

changed line 225 to `"C:/Users/gerry boy/Documents/mpv/ffmpeg.exe",`

Thanks for the help buddy
