### ISSUE TITLE
Option to re-encode audio

### ISSUE THREAD

**Issue by Asinin3** [aerobounce/trim.lua#8]
I use this script to create clips and avoid slow the video encoding process, this works especially well as all the videos I use it with are already compressed. Audio on the other-hand often comes in lossless formats which are very large, and compressing them down is fast and the quality loss can be almost unnoticeable.

Would love to see this script implement some basic options to re-encode the audio out to an AAC format. As I'm still utilizing ffmpeg commands to do trimming on videos with large audio (24-bit flac, LPCM etc)

**Comment by aerobounce** [comment]
Thanks for the suggestion, however, encoding / transcoding is what I would never do with this script by myself.
However, you are absolutely free to fork and make it possible.
