### ISSUE TITLE
Use audio track selected by MPV

### ISSUE THREAD

**Issue by Asinin3** [aerobounce/trim.lua#9]
I have some files with multiple audio tracks, but this script only copies the first track over no matter what I have set in MPV.

**Comment by aerobounce** [comment]
Good point.
Could you try rewrite those lines:
https://github.com/aerobounce/trim.lua/blob/473c9b1a9900c617ee7bb78521906090b15868d4/trim.lua#L399-L401

into:

```lua
        "-c", "copy",
        "-map", "0",
```

**Comment by Asinin3** [comment]
-map 0 will just map every track, so all video, audio, subtitle etc will be copied over.
I suggest looking at https://github.com/ekisu/mpv-webm as this script has the functionality of finding the selected mpv track

**Comment by aerobounce** [comment]
Ah. Excuse me.
However, "Use selected track" will not be happen with this script, as my strong philosophy with this script is to export it as it is — except it is a trim.

Seems you know ffmpeg syntax well, it shouldn't be hard for you to modify the script.
